const LOAD_ALL = "LOAD_ALL";
const LOAD_ALL_SUCCESS = "LOAD_ALL_SUCCESS";
const LOAD_ALL_FAIL = "LOAD_ALL_FAIL";

const LOAD_BRACELETS = "LOAD_BRACELETS";
const LOAD_BRACELETS_SUCCESS = "LOAD_BRACELETS_SUCCESS";
const LOAD_BRACELETS_FAIL = "LOAD_BRACELETS_FAIL";

const LOAD_EARRINGS = "LOAD_EARRINGS";
const LOAD_EARRINGS_SUCCESS = "LOAD_EARRINGS_SUCCESS";
const LOAD_EARRINGS_FAIL = "LOAD_EARRINGS_FAIL";

export {
  LOAD_ALL,
  LOAD_ALL_SUCCESS,
  LOAD_ALL_FAIL,
  LOAD_BRACELETS,
  LOAD_BRACELETS_SUCCESS,
  LOAD_BRACELETS_FAIL,
  LOAD_EARRINGS,
  LOAD_EARRINGS_SUCCESS,
  LOAD_EARRINGS_FAIL,
};
