const CATEGORY_LOAD = 'CATEGORY_LOAD';
const CATEGORY_LOAD_SUCCESS = 'CATEGORY_LOAD_SUCCESS';
const CATEGORY_LOAD_FAIL = 'CATEGORY_LOAD_FAIL';

const BRACELETS_LOAD = 'BRACELETS_LOAD';
const BRACELETS_LOAD_SUCCESS = 'BRACELETS_LOAD_SUCCESS';
const BRACELETS_LOAD_FAIL = 'BRACELETS_LOAD_FAIL';

const EARRINGS_LOAD = 'EARRINGS_LOAD';
const EARRINGS_LOAD_SUCCESS = 'EARRINGS_LOAD_SUCCESS';
const EARRINGS_LOAD_FAIL = 'EARRINGS_LOAD_FAIL';

export {
    CATEGORY_LOAD,
    CATEGORY_LOAD_SUCCESS,
    CATEGORY_LOAD_FAIL,
    BRACELETS_LOAD,
    BRACELETS_LOAD_SUCCESS,
    BRACELETS_LOAD_FAIL,
    EARRINGS_LOAD,
    EARRINGS_LOAD_SUCCESS,
    EARRINGS_LOAD_FAIL,
};
